/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory_Management;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yashi Chaturvedi
 */
public class POS extends javax.swing.JFrame {

    /**
     * Creates new form Brand
     */
    public POS() {
        initComponents();
       // table_update();
    }
    
    String lname;
    
    public POS(String name) {
        initComponents();
      
        
        this.lname = name;
        txtcashier.setText(lname);
       
    }
    
    Connection con1;
    PreparedStatement insert;
    ResultSet rs;
    DefaultTableModel model = new DefaultTableModel();
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        brand_Label = new javax.swing.JLabel();
        pos_Label = new javax.swing.JLabel();
        product_Label = new javax.swing.JLabel();
        exit_Label = new javax.swing.JLabel();
        category_Label = new javax.swing.JLabel();
        cashier_Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtprocode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtproname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        POSTable = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        pay_invoiceButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtcashier = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        brand_Label.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        brand_Label.setForeground(new java.awt.Color(255, 255, 255));
        brand_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brand_Label.setText("Brand");

        pos_Label.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        pos_Label.setForeground(new java.awt.Color(255, 255, 255));
        pos_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pos_Label.setText("Point of Sale");
        pos_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pos_LabelMouseClicked(evt);
            }
        });

        product_Label.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        product_Label.setForeground(new java.awt.Color(255, 255, 255));
        product_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        product_Label.setText("Product");
        product_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_LabelMouseClicked(evt);
            }
        });

        exit_Label.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        exit_Label.setForeground(new java.awt.Color(255, 255, 255));
        exit_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit_Label.setText("Exit");
        exit_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_LabelMouseClicked(evt);
            }
        });

        category_Label.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        category_Label.setForeground(new java.awt.Color(255, 255, 255));
        category_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        category_Label.setText("Category");
        category_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                category_LabelMouseClicked(evt);
            }
        });

        cashier_Label.setFont(new java.awt.Font("Californian FB", 1, 24)); // NOI18N
        cashier_Label.setForeground(new java.awt.Color(255, 255, 255));
        cashier_Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cashier_Label.setText("Cashier");
        cashier_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cashier_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brand_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pos_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(exit_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(product_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(category_Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(cashier_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(category_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(brand_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(product_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pos_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cashier_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SHOE INVENTORY MANAGEMENT SYSTEM");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Point of Sale");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setFont(new java.awt.Font("Modern No. 20", 0, 20)); // NOI18N
        jLabel9.setText("Product Code");

        txtprocode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprocodeActionPerformed(evt);
            }
        });
        txtprocode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtprocodeKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Modern No. 20", 0, 20)); // NOI18N
        jLabel1.setText("Product Name");

        txtproname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpronameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 0, 20)); // NOI18N
        jLabel3.setText("Quantity");

        jLabel4.setFont(new java.awt.Font("Modern No. 20", 0, 20)); // NOI18N
        jLabel4.setText("Price per Piece");

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtprocode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtproname, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtprocode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtproname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        POSTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        POSTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        POSTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Code", "Product Name", "Price/piece", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        POSTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                POSTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(POSTable);

        addButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        addButton.setText("Add");
        addButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Modern No. 20", 0, 20)); // NOI18N
        jLabel10.setText("Subtotal");

        jLabel5.setFont(new java.awt.Font("Modern No. 20", 0, 20)); // NOI18N
        jLabel5.setText("Pay");

        jLabel6.setFont(new java.awt.Font("Modern No. 20", 0, 20)); // NOI18N
        jLabel6.setText("Balance");

        pay_invoiceButton.setFont(new java.awt.Font("Modern No. 20", 0, 24)); // NOI18N
        pay_invoiceButton.setText("Pay Invoice");
        pay_invoiceButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pay_invoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_invoiceButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Modern No. 20", 0, 16)); // NOI18N
        jLabel7.setText(" Cashier : ");

        txtcashier.setFont(new java.awt.Font("Modern No. 20", 0, 16)); // NOI18N
        txtcashier.setForeground(new java.awt.Color(255, 0, 51));
        txtcashier.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(320, 320, 320)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(136, 136, 136)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pay_invoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtcashier))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(addButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(deleteButton)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pay_invoiceButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pos()
    {
        String name = txtprocode.getText();
        try {
                
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/shoeinventorymanagementsystem","root","");
                insert = con1.prepareStatement("select * from product where barcode=?");
                insert.setString(1, name);
                rs = insert.executeQuery();
                
                while(rs.next())
                {
                    int currentqty;
                    currentqty = rs.getInt("Quantity");
                    
                    int price = Integer.parseInt(txtprice.getText());
                    int qtynew = Integer.parseInt(txtqty.getText());
                    
                    int total = price * qtynew;
                    
                    if(qtynew >= currentqty)
                    {
                        JOptionPane.showMessageDialog(this, "Available Quantity = " + currentqty);
                        JOptionPane.showMessageDialog(this, "Quantity is not enough..!!");
                    }
                    else
                    {
                        model = (DefaultTableModel)POSTable.getModel();
                        model.addRow(new Object[]
                        {
                            txtprocode.getText(),
                            txtproname.getText(),
                            txtprice.getText(),
                            txtqty.getText(),
                            total,
                        });
                        
                        int sum = 0;
                        for (int i=0; i<POSTable.getRowCount(); i++)
                        {
                            sum = sum + Integer.parseInt(POSTable.getValueAt(i, 4).toString());
                        }
                        
                        txtsubtotal.setText(Integer.toString(sum));
                        
                        
                        txtprocode.setText("");
                        txtproname.setText("");
                        txtprice.setText("");
                        txtqty.setText("");
                    }
                            
                }
                
             
                
            }
        catch (ClassNotFoundException ex) {
                Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
            }
                
    }
    
    
    
    
    
    
    
    
    private void txtprocodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprocodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprocodeActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        
        pos();
        
        
        
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
       model.removeRow(POSTable.getSelectedRow());
       
       int sum = 0;
       for (int i=0; i<POSTable.getRowCount(); i++)
       {
           sum = sum + Integer.parseInt(POSTable.getValueAt(i, 4).toString());
       }
       
       txtsubtotal.setText(Integer.toString(sum));        
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void category_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_category_LabelMouseClicked
        // TODO add your handling code here:
        
        Category c = new Category();
        this.hide();
        c.setVisible(true);
    }//GEN-LAST:event_category_LabelMouseClicked

    private void POSTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POSTableMouseClicked
        // TODO add your handling code here:

        
        

    }//GEN-LAST:event_POSTableMouseClicked

    private void product_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_LabelMouseClicked
        // TODO add your handling code here:
                
        Product p = new Product();
        this.hide();
        p.setVisible(true);
    }//GEN-LAST:event_product_LabelMouseClicked

    private void txtpronameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpronameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpronameActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void pay_invoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_invoiceButtonActionPerformed
        // TODO add your handling code here:
        
        int pay = Integer.parseInt(txtpay.getText());
        int subtotal = Integer.parseInt(txtsubtotal.getText());
        
        int bal = pay - subtotal;
        
        txtbalance.setText(String.valueOf(bal));
        
        sales();
        print();
    }//GEN-LAST:event_pay_invoiceButtonActionPerformed

     private void sales()
     {
         DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
         LocalDateTime now = LocalDateTime.now();
         String date =dtf.format(now);
         
         String subtotal = txtsubtotal.getText();
         String pay = txtpay.getText();
         String bal = txtbalance.getText();
         String cashier = txtcashier.getText();
         
         int lastinsetid = 0;
         
         try {
            Class.forName("com.mysql.jdbc.Driver");
            con1 = DriverManager.getConnection("jdbc:mysql://localhost/shoeinventorymanagementsystem","root","");
            
            String query = "insert into sales(Date, Cashier, Subtotal, Pay, Balance)values(?, ?, ?, ?, ?)";
            
            insert = con1.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            insert.setString(1, date);
            insert.setString(2, cashier);
            insert.setString(3, subtotal);
            insert.setString(4, pay);
            insert.setString(5, bal);
            insert.executeUpdate();
            
            ResultSet generatedKeyResult = insert.getGeneratedKeys();
            
            if(generatedKeyResult.next())
            {
                lastinsetid = generatedKeyResult.getInt(1);
            }
            
            
            
            int rows = POSTable.getRowCount();
            
            String query1 = "insert into sales_product(Sales_ID, Product_ID, Selling_Price, Quantity, Total)values(?, ?, ?, ?, ?)";
            insert = con1.prepareStatement(query1);
            
            String product_id = "" ;
            String price = "" ;
            String qty = "" ;
            int total = 0;
            
            for(int i = 0; i<POSTable.getRowCount(); i++)
            {
                product_id = (String)POSTable.getValueAt(i, 0);
                price = (String)POSTable.getValueAt(i, 2);
                qty = (String)POSTable.getValueAt(i, 3); 
                total = (int)POSTable.getValueAt(i, 4);
                
                insert.setInt(1, lastinsetid);
                insert.setString(2, product_id); 
                insert.setString(3, price); 
                insert.setString(4, qty);
                insert.setInt(5, total); 
                insert.executeUpdate();
             
            }
           
            String query3 = "update product set Quantity =  Quantity - ? where Barcode = ?";
            insert = con1.prepareStatement(query3);
            
            
            for(int i = 0; i<POSTable.getRowCount(); i++)
            {
                product_id = (String)POSTable.getValueAt(i, 0);               
                qty = (String)POSTable.getValueAt(i, 3); 
              
                
                insert.setString(1, qty);
                insert.setString(2, product_id); 
                
                insert.execute();
             
            }
            
           
            insert.addBatch();
            JOptionPane.showMessageDialog(this, "Record saved");
                    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Brand.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Brand.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
    
    
    
    
    
    
    
    
    
    
    private void txtprocodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprocodeKeyPressed
        // TODO add your handling code here:
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            try {
                String name = txtprocode.getText();
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/shoeinventorymanagementsystem","root","");
                insert = con1.prepareStatement("select * from product where barcode = ?");
                insert.setString(1, name);
                rs = insert.executeQuery();
                
                if(rs.next()==false)
                {
                    JOptionPane.showMessageDialog(this,"Barcode not Found");
                }
                else
                {
                    String productname = rs.getString("Product");
                    String price = rs.getString("Retail_Price");
                    
                    
                    txtproname.setText(productname.trim());
                    txtprice.setText(price.trim());
                    
                    
                }
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        
    }//GEN-LAST:event_txtprocodeKeyPressed

    private void pos_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pos_LabelMouseClicked
        // TODO add your handling code here:
        
        POS pos = new POS();
        this.hide();
        pos.setVisible(true);
    }//GEN-LAST:event_pos_LabelMouseClicked

    private void cashier_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cashier_LabelMouseClicked
        // TODO add your handling code here:
        
        Cashier cashier = new Cashier();
        this.hide();
        cashier.setVisible(true);
    }//GEN-LAST:event_cashier_LabelMouseClicked

    private void exit_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_LabelMouseClicked
        // TODO add your handling code here:
        setVisible(false); //you can't see me!
        dispose(); //Destroy the JFrame object
    }//GEN-LAST:event_exit_LabelMouseClicked

    public void print()
    {
        String sub = txtsubtotal.getText();
        String pay = txtpay.getText();
        String bal = txtbalance.getText();
        
        new Print_Receipt(sub,pay,bal,POSTable.getModel()).setVisible(true);
                
        
        
        
    }

    private void brand_LabelMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        
        Brand b = new Brand();
        this.hide();
        b.setVisible(true);
    }                                    

       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable POSTable;
    private javax.swing.JButton addButton;
    private javax.swing.JLabel brand_Label;
    private javax.swing.JLabel cashier_Label;
    private javax.swing.JLabel category_Label;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel exit_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton pay_invoiceButton;
    private javax.swing.JLabel pos_Label;
    private javax.swing.JLabel product_Label;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JLabel txtcashier;
    private javax.swing.JTextField txtpay;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtprocode;
    private javax.swing.JTextField txtproname;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtsubtotal;
    // End of variables declaration//GEN-END:variables
}
